---
- name: manage_zfs | checking existing zpool(s)
  shell: "zpool list | awk 'FNR >1' | awk '{print $1}'"
  changed_when: false
  register: zpools
  when: zfs_pools is defined
  ignore_errors: "{{ ansible_check_mode }}"

- name: manage_zfs | Gather ZPool Status
  shell: zpool status
  changed_when: false
  register: zpool_devices
  when: zfs_pools is defined
  ignore_errors: "{{ ansible_check_mode }}"

- name: manage_zfs | creating basic zpool(s)
  command: "zpool create {{ item.options | join (' ') if item.options is defined else '' }} {{ item.name }} {{ item.devices|join (' ') }}"
  register: zpool_created
  with_items: "{{ zfs_pools }}"
  when: >
        zfs_pools is defined and
        zfs_create_pools and
        (item.type == "basic" and
        item.name not in zpools.stdout and
        item.state == "present") and
        item.devices[0] not in zpool_devices.stdout and
        item.action|lower == "create"
  ignore_errors: "{{ ansible_check_mode }}"
        
- name: manage_zfs | adding basic zpool(s)
  command: "zpool add {{ '-o' if zfs_pool_options else '' }} {{ zfs_pool_options | join(' -o ') }} {{ item.name }} {{ item.devices|join (' ') }}"
  with_items: "{{ zfs_pools }}"
  when: >
        zfs_pools is defined and
        zfs_create_pools and
        (item.type == "basic" and
        item.state == "present") and
        (item.devices[0]|basename) not in zpool_devices.stdout and
        item.action|lower == "add" and
        (zpool_created.changed or item.name in zpools.stdout)
  ignore_errors: "{{ ansible_check_mode }}"

- name: manage_zfs | creating mirror/zraid zpool(s)
  command: "zpool create {{ '-o' if zfs_pool_options else '' }} {{ zfs_pool_options | join(' -o ') }} {{ '-O' if zfs_fs_options else '' }} {{ zfs_fs_options | join(' -O ') }} {{ item.name }} {{ item.type }} {{ item.devices|join (' ') }}"
  with_items: "{{ zfs_pools }}"
  register: zpool_created
  when: >
        zfs_pools is defined and
        zfs_create_pools and
        (item.type != "basic" and
        item.name not in zpools.stdout and
        item.state == "present") and
        item.devices[0] not in zpool_devices.stdout and
        item.action|lower == "create"
  ignore_errors: "{{ ansible_check_mode }}"

- name: manage_zfs | adding mirror/zraid zpool(s)
  command: "zpool add {{ '-o' if zfs_pool_options else '' }} {{ zfs_pool_options | join(' -o ') }} {{ item.name }} {{ item.type }} {{ item.devices|join (' ') }}"
  with_items: "{{ zfs_pools }}"
  when: >
        zfs_pools is defined and
        zfs_create_pools and
        (item.type != "basic" and
        item.state == "present") and
        (item.devices[0]|basename) not in zpool_devices.stdout and
        item.action|lower == "add" and
        (zpool_created.changed or item.name in zpools.stdout)
  ignore_errors: "{{ ansible_check_mode }}"
