# tasks that involve preparing and managing hosts
version: '3'

# - k0s sysinfo on host

tasks:
  apply-base:
    interactive: true # for interactive scripts
    desc: installs needed apt packages and updated ssh config if/as needed
    deps: []
    summary: |
      long form description of task

      *this* area supports _markdown_
    preconditions: [] # run commands to check 
    vars:
      INVENTORY_PATH: '{{.INVENTORY_PATH | default "inventory/inventory.yaml"}}'
    cmds:
      - ansible-playbook -vv launchpad-core/ansible/site.yaml -i {{.INVENTORY_PATH}} {{.CLI_ARGS}}

  apply-k0s:
    interactive: true # for interactive scripts
    desc: installs k0s on hosts
    deps: []
    summary: |
      long form description of task

      *this* area supports _markdown_
    preconditions: [] # run commands to check 
    vars:
      INVENTORY_PATH: '{{.INVENTORY_PATH | default "inventory/inventory.yaml"}}'
    cmds:
      - ansible-playbook -vv launchpad-core/ansible/install_k0s_cluster.yaml -i {{.INVENTORY_PATH}} {{.CLI_ARGS}}
