# tasks that involve preparing and managing hosts
version: '3'

vars:
  INVENTORY_PATH: '{{.INVENTORY_PATH | default "inventory/inventory.yaml"}}'

tasks:
  apply-base:
    interactive: true
    desc: Performs base host configuration, including package installations and configuring SSH
    cmds:
      - ansible-playbook -vv launchpad-core/ansible/site.yaml --check --diff -i {{.INVENTORY_PATH}} {{.CLI_ARGS}}
      - gum confirm "Simulated changes above. Are you sure you want to continue?"
      - ansible-playbook -vv launchpad-core/ansible/site.yaml -i {{.INVENTORY_PATH}} {{.CLI_ARGS}}

  apply-zfs:
    interactive: true
    desc: Performs base host configuration, including package installations and configuring SSH
    cmds:
      - ansible-playbook -vv launchpad-core/ansible/zfs_install.yaml --check --diff -i {{.INVENTORY_PATH}} {{.CLI_ARGS}}
      - gum confirm "Simulated changes above. Are you sure you want to continue?"
      - ansible-playbook -vv launchpad-core/ansible/zfs_install.yaml -i {{.INVENTORY_PATH}} {{.CLI_ARGS}}

  apply-k0s:
    interactive: true # for interactive scripts
    desc: Joins all hosts into a K0s cluster as defined in the inventory
    cmds:
      # - ansible-playbook -vv launchpad-core/ansible/install_k0s_cluster.yaml --diff -i {{.INVENTORY_PATH}} {{.CLI_ARGS}}
      # - gum confirm "Simulated changes above. Are you sure you want to continue?"
      - ansible-playbook -vv launchpad-core/ansible/install_k0s_cluster.yaml -i {{.INVENTORY_PATH}} {{.CLI_ARGS}}

  # k0s-sysinfo: # TODO add task for running k0s sysinfo on a host/hosts
