# Originally created for k3s-ansible by @jeffspahr
# <https://github.com/k3s-io/k3s-ansible/blob/master/roles/reset/tasks/umount_with_children.yml>
---

- name: Get the list of mounted filesystems
  shell: set -o pipefail && cat /proc/mounts | awk '{ print $2}' | grep -E "^{{ mounted_fs }}"
  register: get_mounted_filesystems
  args:
    executable: /bin/bash
  failed_when: false
  changed_when: get_mounted_filesystems.stdout | length > 0

- name: Umount filesystem
  become: true
  ansible.posix.mount:
    path: "{{ item }}"
    state: absent
  retries: 3
  delay: 5
  register: result
  until: result is not failed
  with_items:
    "{{ get_mounted_filesystems.stdout_lines }}"
