# example of multi-nodes HA k8s inventory

base:
  hosts: &all
    worker_0:
      ansible_host: <ip>
    worker_1:
      ansible_host: <ip>
    worker_2:
      ansible_host: <ip>
    control-plane-0:
      ansible_host: <ip>
    control-plane-1:
      ansible_host: <ip>
    control-plane-2:
      ansible_host: <ip>

ssh:
  hosts: *all

k0s:
  children:
    initial_controller:
      hosts:
        control-plane-0:
    controller:
      hosts:   
        control-plane-1:
        control-plane-2:
    worker:
      hosts:
        worker_0:
        worker_1:
        worker_2:
  hosts: *all

---
# example of inventory for single node setup
base:
  hosts: &all
    control-plane-0:
      ansible_host: <ip>

ssh:
  hosts: *all

k0s:
  children:
    initial_controller:
      hosts:
        control-plane-0:
  hosts: *all