---
# As upgrading a node  requires special attention,
# this block uses an inventory on the fly with add_host
# to prompt the user for hostname
- hosts: localhost
  gather_facts: yes

  tasks:
  - name: get hosts
    local_action:
      module: shell
      _raw_params: "kubectl --kubeconfig $KUBECONFIG get nodes"
    become: false
    register: k0s_workers

  - name: verbose
    ansible.builtin.debug:
     msg:
      - "The following playbook allows you to upgrade the k0s version on nodes safely and one at a time"
      - "Make sure you first update the k0s_version variable value in your inventory."
      - "If you are upgrading a k0s controller node check inventory for the desired hostname."
      - "The k0s worker nodes in your current cluster are:"

  - name: nodes
    ansible.builtin.debug:
     msg:
      - "{{ item }}"
    with_items: "{{ k0s_workers.stdout_lines }}"

  - name: target_host
    pause:
      prompt: "Specify which node to upgrade:"
      echo: yes
    register: target_host
    
  - add_host:
      name: "{{ target_host.user_input }}"
      groups: dynamically_created_hosts

  - set_fact:
      target_host: "{{ target_host.user_input }}"

# End of inventory on the fly block
  - ansible.builtin.debug:
     msg:
      - "{{ target_host }}"

  - name: drain node
    local_action:
      module: shell
      _raw_params: "kubectl --kubeconfig $KUBECONFIG drain {{ target_host }} --disable-eviction=true --force --ignore-daemonsets --delete-emptydir-data"
    become: false
    register: node_drain_out

  - name: set k8s_version_upgrade_eviction_seconds fact
    set_fact:
      k8s_version_upgrade_eviction_seconds: 45
    run_once: true
    when: k8s_version_upgrade_eviction_seconds is undefined

  - name: allow some time for the evictions
    pause:
      seconds: "{{ k8s_version_upgrade_eviction_seconds }}"

- hosts: dynamically_created_hosts
  name: "Upgrading k0s version"
  become: yes
  tasks:
    - shell: k0s stop

- hosts: dynamically_created_hosts
  name: Download new version of k0s 
  become: yes
  roles:
    - role: k0s/download
      tags: download

- hosts: dynamically_created_hosts
  name: start the k0s service
  become: yes
  tasks:
    - shell: k0s start 

- hosts: localhost
  gather_facts: yes
  tasks:
  - name: Sleep for 30 seconds to give k0s a chance to start up
    ansible.builtin.wait_for:
     timeout: 30
  - name: uncordon node
    local_action:
      module: shell
      _raw_params: "kubectl --kubeconfig $KUBECONFIG uncordon {{ target_host }}"
    become: false