# Repositories for Charts used for Releases in this namespace
repositories:
  - name: graphops
    url: https://graphops.github.io/launchpad-charts

# Anchors for each default release definition, their default values, and any inner resources that are relevant
templates:
  launchpad-release-template-defaults: &launchpad-release-template-defaults
    namespace: avalanche-mainnet
    missingFileHandler: Warn

  launchpad-release-template-resource-injector: &launchpad-release-template-resource-injector
    <<: *launchpad-release-template-defaults
    chart: graphops/resource-injector
    version: 0.2.0

  launchpad-release-template-avalanche-archive-trace-mainnet: &launchpad-release-template-avalanche-archive-trace-mainnet
    <<: *launchpad-release-template-defaults
    chart: graphops/avalanche
    version: 0.1.0

  launchpad-release-template-proxyd-avalanche-mainnet: &launchpad-release-template-proxyd-avalanche-mainnet
    <<: *launchpad-release-template-defaults
    chart: graphops/proxyd
    version: 0.1.8