# Repositories for Charts used for Releases in this namespace
repositories:
  - name: graphops
    url: https://graphops.github.io/launchpad-charts

# Anchors for each default release definition, their default values, and any inner resources that are relevant
templates:
  launchpad-release-template-defaults: &launchpad-release-template-defaults
    namespace: gnosis-mainnet
    missingFileHandler: Warn

  launchpad-release-template-resource-injector: &launchpad-release-template-resource-injector
    <<: *launchpad-release-template-defaults
    chart: graphops/resource-injector
    version: 0.2.0

  launchpad-release-template-nethermind-gnosis-mainnet: &launchpad-release-template-nethermind-gnosis-mainnet
    <<: *launchpad-release-template-defaults
    chart: graphops/nethermind
    version: 0.2.0

  launchpad-release-template-nimbus-gnosis-mainnet: &launchpad-release-template-nimbus-gnosis-mainnet
    <<: *launchpad-release-template-defaults
    chart: graphops/nimbus
    version: 0.3.0

  launchpad-release-template-proxyd-gnosis-mainnet: &launchpad-release-template-proxyd-gnosis-mainnet
    <<: *launchpad-release-template-defaults
    chart: graphops/proxyd
    version: 0.1.8
