# Repositories for Charts used for Releases in this namespace
repositories:
  - name: graphops
    url: https://graphops.github.io/helm-charts
  - name: graph-node-chart-dev
    url: git+https://github.com/graphops/helm-charts@charts?ref=feature/graph-node
  - name: graph-network-indexer-chart-dev
    url: git+https://github.com/graphops/helm-charts@charts?ref=graph-network-indexer/init

# Anchors for each default release definition, their default values, and any inner resources that are relevant
templates:
  launchpad-release-template-defaults: &launchpad-release-template-defaults
    namespace: graph-goerli
    missingFileHandler: Warn
  launchpad-release-template-postgresql-cr: &launchpad-release-template-postgresql-cr
    <<: *launchpad-release-template-defaults
    chart: graphops/resource-injector
    version: 0.2.0

  launchpad-release-template-graph-node: &launchpad-release-template-graph-node
    <<: *launchpad-release-template-defaults
    chart: graph-node-chart-dev/graph-node
    # version: 4.2.1

  launchpad-release-template-graph-network-indexer: &launchpad-release-template-graph-network-indexer
    <<: *launchpad-release-template-defaults
    chart: graph-network-indexer-chart-dev/graph-network-indexer
    # version: 4.2.1
