# Repositories for Charts used for Releases in this namespace
repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: vouch
    url: https://vouch.github.io/helm-charts/

# Anchors for each default release definition, their default values, and any inner resources that are relevant
templates:
  launchpad-release-template-defaults: &launchpad-release-template-defaults
    namespace: ingress
    missingFileHandler: Warn
  launchpad-release-template-ingress-nginx: &launchpad-release-template-ingress-nginx
    <<: *launchpad-release-template-defaults
    chart: ingress-nginx/ingress-nginx
    version: 4.3.0
    labels:
      component: ingress-nginx
    valuesTemplate:
      - &launchpad-default-release-values-ingress-nginx {}
