repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

# todo: document using the values hack to define templates
values:
  - template-default-namespace-name: &template-default-namespace-name ingress
  #### TEMPLATES FOR EACH RELEASE IN NAMESPACE
  - template-default-release-ingress-nginx: &template-default-release-ingress-nginx
      namespace: *template-default-namespace-name
      chart: ingress-nginx/ingress-nginx
      version: 4.2.1
      values:
      - &template-default-values-ingress-nginx {}
  #### TEMPLATE FOR ALL RELEASES IN NAMESPACE
  # template-default-<namespace>-releases
  - template-default-ingress-releases: &template-default-ingress-releases
      releases:
        - name: ingress-nginx
          <<: *template-default-release-ingress-nginx