# Repositories for Charts used for Releases in this namespace
repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

templates:
  launchpad-release-template-ingress-nginx: &launchpad-release-template-ingress-nginx
    namespace: &template-default-ingress-namespace-name ingress
    chart: ingress-nginx/ingress-nginx
    version: 4.2.1
    labels:
      component: ingress-nginx
    valuesTemplate:
      - &launchpad-default-release-values-ingress-nginx {}