# Repositories for Charts used for Releases in this namespace
repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: prometheus
    url: https://prometheus-community.github.io/helm-charts
  - name: graphops
    url: https://graphops.github.io/helm-charts

templates:
  launchpad-release-template-promtail: &launchpad-release-template-promtail
    namespace: &template-default-monitoring-namespace-name monitoring
    chart: grafana/promtail
    version: 6.2.3
    labels:
      component: promtail
    valuesTemplate:
      - &launchpad-default-release-values-promtail {}

  launchpad-release-template-grafana: &launchpad-release-template-grafana
    namespace: *template-default-monitoring-namespace-name
    chart: grafana/grafana
    version: 6.32.14
    labels:
      component: grafana
    # version: 0.0.0 # Specify the version by pinning the git repo reference in repositories above
    valuesTemplate:
      - &launchpad-default-release-values-grafana {}

  launchpad-release-template-prometheus: &launchpad-release-template-prometheus
    namespace: *template-default-monitoring-namespace-name
    chart: prometheus/prometheus
    version: 15.12.0
    labels:
      component: prometheus
    valuesTemplate:
      - &launchpad-default-release-values-prometheus {}

  launchpad-release-template-loki-secret: &launchpad-release-template-loki-secret
    namespace: *template-default-monitoring-namespace-name
    chart: graphops/resource-injector
    version: 0.1.0
    valuesTemplate:
      - &launchpad-default-release-values-loki-secret {}

  launchpad-release-template-loki: &launchpad-release-template-loki
    namespace: *template-default-monitoring-namespace-name
    chart: grafana/loki-distributed
    version: 0.55.4 
    labels:
      component: loki
    # version: 0.0.0 # Specify the version by pinning the git repo reference in repositories above
    valuesTemplate:
      - &launchpad-default-release-values-loki {}
