repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: prometheus
    url: https://prometheus-community.github.io/helm-charts
  - name: graphops
    url: https://graphops.github.io/helm-charts

# todo: document using the values hack to define templates
values:
  - template-default-namespace-name: &template-default-namespace-name monitoring
  #### TEMPLATES FOR EACH RELEASE IN NAMESPACE
  - template-default-release-promtail: &template-default-release-promtail
      namespace: *template-default-namespace-name
      chart: grafana/promtail
      version: 6.2.3
      labels:
        component: promtail #is this needed
      values:
      - &template-default-release-promtail {}
      
  - template-default-release-grafana: &template-default-release-grafana
      namespace: *template-default-namespace-name
      chart: grafana/grafana
      version: 6.32.14
      labels:
        component: grafana
      values:
      - &template-default-release-grafana {}

  - template-default-release-prometheus: &template-default-release-prometheus
      namespace: *template-default-namespace-name
      chart: prometheus/prometheus
      version: 15.12.0
      labels:
        component: prometheus
      values:
      - &template-default-values-prometheus {}

  - template-default-release-loki-secret: &template-default-release-loki-secret
      namespace: *template-default-namespace-name
      chart: graphops/resource-injector
      version: 0.1.0
      values:
      - &template-default-values-loki-secret {}

  - template-default-release-loki: &template-default-release-loki
      namespace: *template-default-namespace-name
      chart: grafana/loki-distributed
      version: 0.55.4 
      labels:
        component: loki
      values:
      - &template-default-values-loki {}

  #### TEMPLATE FOR ALL RELEASES IN NAMESPACE
  # template-default-<namespace>-releases
  - template-default-monitoring-releases: &template-default-monitoring-releases
      releases:
        - name: promtail
          <<: *template-default-release-promtail
        - name: grafana
          <<: *template-default-release-grafana
        - name: prometheus
          <<: *template-default-release-prometheus
        - name: loki-secret
          <<: *template-default-release-loki-secret
        - name: loki
          <<: *template-default-release-loki
        
        