# Repositories for Charts used for Releases in this namespace
repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: deliveryhero
    url: https://charts.deliveryhero.io
  - name: graphops
    url: https://graphops.github.io/helm-charts

# Anchors for each default release definition, their default values, and any inner resources that are relevant
templates: # TODO replace with https://github.com/prometheus-operator/kube-prometheus, add node-problem-detector
  launchpad-release-template-defaults: &launchpad-release-template-defaults
    namespace: monitoring
    missingFileHandler: Warn

  launchpad-release-template-kube-prometheus-stack: &launchpad-release-template-kube-prometheus-stack
    <<: *launchpad-release-template-defaults
    chart: prometheus-community/kube-prometheus-stack
    version: 39.9.0
    valuesTemplate:
      - &launchpad-default-release-values-kube-prometheus-stack {} # TODO Enable scrape annotations on objects

  launchpad-release-template-node-problem-detector: &launchpad-release-template-node-problem-detector
    <<: *launchpad-release-template-defaults
    chart: deliveryhero/node-problem-detector
    version: 2.2.3
    valuesTemplate:
      - &launchpad-default-release-values-node-problem-detector {} # TODO Enable scrape annotations on objects

  launchpad-release-template-promtail: &launchpad-release-template-promtail
    <<: *launchpad-release-template-defaults
    chart: grafana/promtail
    version: 6.2.3
    labels:
      component: promtail
    valuesTemplate:
      - &launchpad-default-release-values-promtail {}

  launchpad-release-template-loki-secret: &launchpad-release-template-loki-secret
    <<: *launchpad-release-template-defaults
    chart: graphops/resource-injector
    version: 0.1.0
    valuesTemplate:
      - &launchpad-default-release-values-loki-secret {}

  launchpad-release-template-loki: &launchpad-release-template-loki
    <<: *launchpad-release-template-defaults
    chart: grafana/loki-distributed
    version: 0.55.4
    # version: 0.0.0 # Specify the version by pinning the git repo reference in repositories above
    valuesTemplate:
      - &launchpad-default-release-values-loki {}
