# Repositories for Charts used for Releases in this namespace
repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: prometheus
    url: https://prometheus-community.github.io/helm-charts
  - name: graphops
    url: https://graphops.github.io/helm-charts

# Anchors for each default release definition, their default values, and any inner resources that are relevant
templates: # TODO replace with https://github.com/prometheus-operator/kube-prometheus, add node-problem-detector
  launchpad-release-template-defaults: &launchpad-release-template-defaults
    namespace: monitoring
    missingFileHandler: Warn
  launchpad-release-template-promtail: &launchpad-release-template-promtail
    <<: *launchpad-release-template-defaults
    chart: grafana/promtail
    version: 6.2.3
    labels:
      component: promtail
    valuesTemplate:
      - &launchpad-default-release-values-promtail {}

  launchpad-release-template-grafana: &launchpad-release-template-grafana
    <<: *launchpad-release-template-defaults
    chart: grafana/grafana
    version: 6.32.14
    labels:
      component: grafana
    # version: 0.0.0 # Specify the version by pinning the git repo reference in repositories above
    valuesTemplate:
      - &launchpad-default-release-values-grafana {} # TODO disable auth, enable dashboard and datasource finding across all NS

  launchpad-release-template-prometheus: &launchpad-release-template-prometheus
    <<: *launchpad-release-template-defaults
    chart: prometheus/prometheus
    version: 15.12.0
    labels:
      component: prometheus
    valuesTemplate:
      - &launchpad-default-release-values-prometheus {} # TODO Enable scrape annotations on objects

  launchpad-release-template-loki-secret: &launchpad-release-template-loki-secret
    <<: *launchpad-release-template-defaults
    chart: graphops/resource-injector
    version: 0.1.0
    valuesTemplate:
      - &launchpad-default-release-values-loki-secret {}

  launchpad-release-template-loki: &launchpad-release-template-loki
    <<: *launchpad-release-template-defaults
    chart: grafana/loki-distributed
    version: 0.55.4
    labels:
      component: loki
    # version: 0.0.0 # Specify the version by pinning the git repo reference in repositories above
    valuesTemplate:
      - &launchpad-default-release-values-loki {}
