# Repositories for Charts used for Releases in this namespace
repositories:
  - name: postgres-operator-charts
    url: https://opensource.zalando.com/postgres-operator/charts/postgres-operator

templates:
  launchpad-release-template-postgres-operator: &launchpad-release-template-postgres-operator
    namespace: &template-default-postgres-operator-namespace-name postgres-operator
    chart: postgres-operator-charts/postgres-operator
    version: 1.8.2
    disableValidationOnInstall: true # https://github.com/roboll/helmfile/issues/1600
    labels:
      component: postgres-operator
    valuesTemplate:
      - &launchpad-default-release-values-postgres-operator {}