repositories:
  - name: postgres-operator-charts
    url: https://opensource.zalando.com/postgres-operator/charts/postgres-operator

releases:
  - name: postgres-operator
    namespace: &namespace postgres-operator
    chart: postgres-operator-charts/postgres-operator
    version: 1.8.2
    disableValidationOnInstall: true # https://github.com/roboll/helmfile/issues/1600