# Repositories for Charts used for Releases in this namespace
repositories:
  - name: postgres-operator-charts
    url: https://opensource.zalando.com/postgres-operator/charts/postgres-operator

# Anchors for each default release definition, their default values, and any inner resources that are relevant
templates:
  launchpad-release-template-defaults: &launchpad-release-template-defaults
    namespace: postgres-operator
    missingFileHandler: Warn
  launchpad-release-template-postgres-operator: &launchpad-release-template-postgres-operator
    <<: *launchpad-release-template-defaults
    chart: postgres-operator-charts/postgres-operator
    version: 1.8.2
    disableValidationOnInstall: true # https://github.com/roboll/helmfile/issues/1600
