# Repositories for Charts used for Releases in this namespace
repositories:
  - name: sealed-secrets
    url: https://bitnami-labs.github.io/sealed-secrets

# In order to allow for a high degree of flexibility in launchpad-starter, we use YAML templating (not Helmfile templates)
# to define a rich set of templates that can be composed by downstream YAML into the desired configuration.
# Helmfile validates the content of any Helmfile YAML against a strictly defined and typed schema. The only key in that
# schema that supports arbitrary YAML is the `values` key, which is of type `[]interface{}`. Therefore, we define our
# YAML templates and their anchors in this key, but they are not intended to be used as Helmfile Values.
values:
  - x-launchpad-templates:
      # An anchor for the name of the namespace
      template-default-sealed-secrets-namespace-name: &template-default-sealed-secrets-namespace-name sealed-secrets

      # Anchors for each default release definition
      template-default-release-sealed-secrets: &template-default-release-sealed-secrets
        namespace: *template-default-sealed-secrets-namespace-name
        chart: sealed-secrets/sealed-secrets
        version: 2.6.0
        labels:
          component: sealed-secrets
        values:
        - &template-default-values-ingress-nginx {}

      # An anchor for the default releases definition for this namespace
      template-default-ingress-releases: &template-default-sealed-secrets-releases
        releases:
          - name: sealed-secrets
            <<: *template-default-release-sealed-secrets