# Repositories for Charts used for Releases in this namespace
repositories:
  - name: sealed-secrets
    url: https://bitnami-labs.github.io/sealed-secrets

# Anchors for each default release definition, their default values, and any inner resources that are relevant
templates:
  launchpad-release-template-defaults: &launchpad-release-template-defaults
    namespace: sealed-secrets
    missingFileHandler: Warn
  launchpad-release-template-sealed-secrets: &launchpad-release-template-sealed-secrets
    <<: *launchpad-release-template-defaults
    chart: sealed-secrets/sealed-secrets
    version: 2.6.7
