repositories:
  - name: sealed-secrets
    url: https://bitnami-labs.github.io/sealed-secrets

# todo: document using the values hack to define templates
values:
  - template-default-namespace-name: &template-default-namespace-name sealed-secrets
  #### TEMPLATES FOR EACH RELEASE IN NAMESPACE
  - template-default-release-sealed-secrets: &template-default-release-sealed-secrets
      namespace: *template-default-namespace-name
      chart: sealed-secrets/sealed-secrets
      version: 2.6.0
      labels:
        component: sealed-secrets
      values:
      - &template-default-values-ingress-nginx {}
  #### TEMPLATE FOR ALL RELEASES IN NAMESPACE
  # template-default-<namespace>-releases
  - template-default-ingress-releases: &template-default-sealed-secrets-releases
      releases:
        - name: sealed-secrets
          <<: *template-default-release-sealed-secrets