# Repositories for Charts used for Releases in this namespace
repositories:
  - name: sealed-secrets
    url: https://bitnami-labs.github.io/sealed-secrets

# Anchors for each default release definition, their default values, and any inner resources that are relevant
templates:
  launchpad-release-template-sealed-secrets: &launchpad-release-template-sealed-secrets
    namespace: &template-default-sealed-secrets-namespace-name sealed-secrets
    chart: sealed-secrets/sealed-secrets
    version: 2.6.0
    labels:
      component: sealed-secrets
    valuesTemplate:
      - &launchpad-default-release-values-ingress-nginx
        grafana:
          enabled: true
