# Repositories for Charts used for Releases in this namespace
repositories:
  - name: openebs
    url: https://openebs.github.io/charts
  - name: openebs-zfs-localpv
    url: https://openebs.github.io/zfs-localpv
  - name: openebs-monitoring
    url: https://openebs.github.io/monitoring/
  - name: graphops
    url: https://graphops.github.io/helm-charts

# Anchors for each default release definition, their default values, and any inner resources that are relevant
templates:
  launchpad-release-template-defaults: &launchpad-release-template-defaults
    namespace: storage
    missingFileHandler: Warn
  launchpad-release-template-openebs: &launchpad-release-template-openebs
    namespace: &template-default-storage-namespace-name storage
    chart: openebs/openebs
    version: 3.3.0

  launchpad-release-template-openebs-rawfile-localpv: &launchpad-release-template-openebs-rawfile-localpv
    <<: *launchpad-release-template-defaults
    chart: graphops/openebs-rawfile-localpv
    version: 0.8.0

  launchpad-release-template-openebs-rawfile-storageclass: &launchpad-release-template-openebs-rawfile-storageclass
    <<: *launchpad-release-template-defaults
    chart: graphops/resource-injector
    version: 0.2.0

  launchpad-release-template-openebs-zfs-localpv: &launchpad-release-template-openebs-zfs-localpv
    <<: *launchpad-release-template-defaults
    chart: openebs-zfs-localpv/zfs-localpv
    version: 2.1.0

  launchpad-release-template-openebs-zfs-storageclass: &launchpad-release-template-openebs-zfs-storageclass
    <<: *launchpad-release-template-defaults
    chart: graphops/resource-injector
    version: 0.2.0

  launchpad-release-template-openebs-monitoring: &launchpad-release-template-openebs-monitoring
    <<: *launchpad-release-template-defaults
    chart: openebs-monitoring/openebs-monitoring
    version: 0.4.10
