repositories:
  - name: openebs
    url: https://openebs.github.io/charts
  - name: openebs-zfslocalpv
    url: https://openebs.github.io/zfs-localpv
  # - name: openebs-rawfile
  #   git
  - name: graphops
    url: https://graphops.github.io/helm-charts

releases: 
  - name: openebs
    namespace: &namespace "storage"
    chart: openebs/openebs
    version: 3.3.0

  - name: openebs-zfs
    namespace: *namespace
    chart: openebs-zfslocalpv/zfs-localpv
    version: 2.1.0

  # - name: openebs-rawfile
  #   namespace: *namespace
  #   chart: openebs-rawfile/rawfile-csi
  #   version: 0.7.0

  - name: openebs-zfs-storageclass
    namespace: *namespace
    chart: graphops/resource-injector
    version: 0.1.0
