---

- name: Disable k0s service
  become: true
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  failed_when: false
  with_items:
    - k0scontroller
    - k0sworker

- name: Ensure no other k0s services are running
  ignore_errors: yes
  shell: "ps -few | grep [k]0s| awk '{print $2}'"
  register: running_processes

- name: Kill running processes
  ignore_errors: yes
  shell: "kill {{ item }}"
  with_items: "{{ running_processes.stdout_lines }}"

- name: Umount k0s filesystems
  include_tasks: umount_with_children.yml
  with_items:
    - "{{ k0s_data_dir }}"
    - "{{ k0s_libexec_dir }}"
    - "{{ k0s_config_dir }}"
    # - /var/lib/kubelet
    # - /run/k0s
  loop_control:
    loop_var: mounted_fs

- name: Remove k0s Directories
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ k0s_config_dir }}"
    - "{{ k0s_data_dir }}"
    - "{{ k0s_libexec_dir }}"
    - "{{ k0s_binary_dest }}"
    # - /var/lib/kubelet
    # - /run/k0s
    - "{{ systemd_dest }}/k0scontroller.service"
    - "{{ systemd_dest }}/k0sworker.service"
  retries: 5
  delay: 5
  register: result
  until: result is not failed

- name: daemon_reload
  become: true
  command: systemctl daemon-reload
  # systemd:
  #   daemon_reload: yes
